# Generated by Django 4.2.5 on 2023-11-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('AlbumID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('ReleaseDate', models.DateField()),
                ('LengthMins', models.IntegerField()),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('ArtistID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('GenreID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('RatingID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30)),
                ('Rating', models.IntegerField()),
                ('AlbumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicThing.albums')),
            ],
        ),
        migrations.AddField(
            model_name='albums',
            name='ArtistID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicThing.artists'),
        ),
        migrations.AddField(
            model_name='albums',
            name='GenreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicThing.genres'),
        ),
    ]
